# Generated by Django 5.0.4 on 2024-05-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_authors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Производитель')),
                ('country_manufacturer', models.CharField(max_length=50, verbose_name='Страна происхождения')),
                ('article_number', models.IntegerField(verbose_name='Артикул')),
                ('manufactured_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изготовления')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'Офисные принадлежности',
            },
        ),
        migrations.CreateModel(
            name='EBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна производства')),
                ('article_number', models.IntegerField(verbose_name='Артикул')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('features', models.TextField(verbose_name='Описание')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Электронная книга',
                'verbose_name_plural': 'Электронные книги',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_set', to='bookshop.authors', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_set', to='bookshop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='clip_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Скрепка',
                'verbose_name_plural': 'Скрепки',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='envelope_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Конверт',
                'verbose_name_plural': 'Конверты',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marker_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Маркер',
                'verbose_name_plural': 'Маркеры',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notebook_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Блокнот',
                'verbose_name_plural': 'Блокноты',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paint_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name_plural': 'Краски для рисования',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paper_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Бумага',
                'verbose_name_plural': 'Бумага',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pen_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Ручка',
                'verbose_name_plural': 'Ручки',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='Pencil',
            fields=[
                ('officesupplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bookshop.officesupplies')),
                ('office_supplies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pencil_set', serialize=False, to='bookshop.officesupplies')),
            ],
            options={
                'verbose_name': 'Карандаш',
                'verbose_name_plural': 'Карандаши',
            },
            bases=('bookshop.officesupplies',),
        ),
        migrations.CreateModel(
            name='EBooks_other_shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазинов')),
                ('ebooks', models.ManyToManyField(related_name='ebookshops', to='bookshop.ebooks', verbose_name='Электронные книги')),
            ],
        ),
        migrations.AddField(
            model_name='ebooks',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks_set', to='bookshop.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='ebooks',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks_set', to='bookshop.model', verbose_name='Модель'),
        ),
    ]
